services:
  apivttech-backend:
    image: apivttech-apivttech-backend:latest
    build:
      context: .
      dockerfile: ./backend-api/Dockerfile
    container_name: apivttech-backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:12003/db_tazagroup_vttech_sync
      - REDIS_HOST=shared-redis
      - REDIS_PORT=6379
      - PORT=5001
      - NODE_ENV=production
      - TZ=Asia/Ho_Chi_Minh
      - VTTECH_ACCOUNTS=ittest1:ittest1,ittest2:ittest2,ittest3:ittest3,ittest4:ittest4
      - VTTECH_BASE_URL=https://tmtaza.vttechsolution.com
    ports:
      - "21101:5001"
    networks:
      - taza-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  apivttech-dashboard:
    image: apivttech-apivttech-dashboard:latest
    build:
      context: .
      dockerfile: ./vttech-dashboard/Dockerfile
    container_name: apivttech-dashboard
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:12003/db_tazagroup_vttech_sync
      - NODE_ENV=production
      - TZ=Asia/Ho_Chi_Minh
      - PORT=5000
    ports:
      - "21100:5000"
    networks:
      - taza-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  shared-redis:
    image: redis:alpine
    restart: always
    ports:
      - "26380:6379"
    networks:
      - taza-network

networks:
  taza-network:
    external: true
