services:
  apivttech-backend:
    build:
      context: .
      dockerfile: ./backend-api/Dockerfile
    container_name: apivttech-backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@shared-db:5432/db_tazagroup_vttech_sync
      - REDIS_HOST=shared-redis
      - REDIS_PORT=6379
      - PORT=5001
      - NODE_ENV=production
      - TZ=Asia/Ho_Chi_Minh
      - VTTECH_USERNAME=ittest123
      - VTTECH_PASSWORD=ittest123
      - VTTECH_BASE_URL=https://tmtaza.vttechsolution.com
    ports:
      - "21101:5001"
    networks:
      - kata-cells-network
      - rausach-network
      - taza-network

  apivttech-dashboard:
    build:
      context: .
      dockerfile: ./vttech-dashboard/Dockerfile
    container_name: apivttech-dashboard
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@shared-db:5432/db_tazagroup_vttech_sync
      - NODE_ENV=production
      - TZ=Asia/Ho_Chi_Minh
      - PORT=5000
    ports:
      - "21100:5000"
    networks:
      - kata-cells-network
      - rausach-network
      - taza-network

networks:
  kata-cells-network:
    external: true
  rausach-network:
    external: true
  taza-network:
    external: true
