# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template models.py.jinja --
from pydantic import BaseModel

from . import fields, actions
from ._types import FuncType
from ._builder import serialize_base64
from ._compat import PYDANTIC_V2, ConfigDict

if TYPE_CHECKING:
    from .client import Prisma


_PrismaModelT = TypeVar('_PrismaModelT', bound='_PrismaModel')


class _PrismaModel(BaseModel):
    if PYDANTIC_V2:
        model_config: ClassVar[ConfigDict] = ConfigDict(
            use_enum_values=True,
            arbitrary_types_allowed=True,
            populate_by_name=True,
        )
    elif not TYPE_CHECKING:
        from ._compat import BaseConfig

        class Config(BaseConfig):
            use_enum_values: bool = True
            arbitrary_types_allowed: bool = True
            allow_population_by_field_name: bool = True
            json_encoders: Dict[Any, FuncType] = {
                fields.Base64: serialize_base64,
            }

    # TODO: ensure this is required by subclasses
    __prisma_model__: ClassVar[str]


class BaseBranch(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Branch']] = 'Branch'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.BranchActions[_PrismaModelT]':
        from .client import get_client

        return actions.BranchActions[_PrismaModelT](client or get_client(), cls)


class BaseService(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Service']] = 'Service'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ServiceActions[_PrismaModelT]':
        from .client import get_client

        return actions.ServiceActions[_PrismaModelT](client or get_client(), cls)


class BaseServiceGroup(_PrismaModel):
    __prisma_model__: ClassVar[Literal['ServiceGroup']] = 'ServiceGroup'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ServiceGroupActions[_PrismaModelT]':
        from .client import get_client

        return actions.ServiceGroupActions[_PrismaModelT](client or get_client(), cls)


class BaseServiceType(_PrismaModel):
    __prisma_model__: ClassVar[Literal['ServiceType']] = 'ServiceType'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ServiceTypeActions[_PrismaModelT]':
        from .client import get_client

        return actions.ServiceTypeActions[_PrismaModelT](client or get_client(), cls)


class BaseEmployee(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Employee']] = 'Employee'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.EmployeeActions[_PrismaModelT]':
        from .client import get_client

        return actions.EmployeeActions[_PrismaModelT](client or get_client(), cls)


class BaseEmployeeGroup(_PrismaModel):
    __prisma_model__: ClassVar[Literal['EmployeeGroup']] = 'EmployeeGroup'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.EmployeeGroupActions[_PrismaModelT]':
        from .client import get_client

        return actions.EmployeeGroupActions[_PrismaModelT](client or get_client(), cls)


class BaseUser(_PrismaModel):
    __prisma_model__: ClassVar[Literal['User']] = 'User'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.UserActions[_PrismaModelT]':
        from .client import get_client

        return actions.UserActions[_PrismaModelT](client or get_client(), cls)


class BaseCustomerSource(_PrismaModel):
    __prisma_model__: ClassVar[Literal['CustomerSource']] = 'CustomerSource'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.CustomerSourceActions[_PrismaModelT]':
        from .client import get_client

        return actions.CustomerSourceActions[_PrismaModelT](client or get_client(), cls)


class BaseMembership(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Membership']] = 'Membership'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.MembershipActions[_PrismaModelT]':
        from .client import get_client

        return actions.MembershipActions[_PrismaModelT](client or get_client(), cls)


class BaseCity(_PrismaModel):
    __prisma_model__: ClassVar[Literal['City']] = 'City'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.CityActions[_PrismaModelT]':
        from .client import get_client

        return actions.CityActions[_PrismaModelT](client or get_client(), cls)


class BaseDistrict(_PrismaModel):
    __prisma_model__: ClassVar[Literal['District']] = 'District'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.DistrictActions[_PrismaModelT]':
        from .client import get_client

        return actions.DistrictActions[_PrismaModelT](client or get_client(), cls)


class BaseWard(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Ward']] = 'Ward'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.WardActions[_PrismaModelT]':
        from .client import get_client

        return actions.WardActions[_PrismaModelT](client or get_client(), cls)


class BaseDailyRevenue(_PrismaModel):
    __prisma_model__: ClassVar[Literal['DailyRevenue']] = 'DailyRevenue'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.DailyRevenueActions[_PrismaModelT]':
        from .client import get_client

        return actions.DailyRevenueActions[_PrismaModelT](client or get_client(), cls)


class BaseCustomer(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Customer']] = 'Customer'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.CustomerActions[_PrismaModelT]':
        from .client import get_client

        return actions.CustomerActions[_PrismaModelT](client or get_client(), cls)


class BaseDailyCustomer(_PrismaModel):
    __prisma_model__: ClassVar[Literal['DailyCustomer']] = 'DailyCustomer'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.DailyCustomerActions[_PrismaModelT]':
        from .client import get_client

        return actions.DailyCustomerActions[_PrismaModelT](client or get_client(), cls)


class BaseAppointment(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Appointment']] = 'Appointment'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AppointmentActions[_PrismaModelT]':
        from .client import get_client

        return actions.AppointmentActions[_PrismaModelT](client or get_client(), cls)


class BaseTreatment(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Treatment']] = 'Treatment'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.TreatmentActions[_PrismaModelT]':
        from .client import get_client

        return actions.TreatmentActions[_PrismaModelT](client or get_client(), cls)


class BaseCrawlLog(_PrismaModel):
    __prisma_model__: ClassVar[Literal['CrawlLog']] = 'CrawlLog'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.CrawlLogActions[_PrismaModelT]':
        from .client import get_client

        return actions.CrawlLogActions[_PrismaModelT](client or get_client(), cls)


class BaseCustomerPayment(_PrismaModel):
    __prisma_model__: ClassVar[Literal['CustomerPayment']] = 'CustomerPayment'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.CustomerPaymentActions[_PrismaModelT]':
        from .client import get_client

        return actions.CustomerPaymentActions[_PrismaModelT](client or get_client(), cls)


class BaseCustomerInstallment(_PrismaModel):
    __prisma_model__: ClassVar[Literal['CustomerInstallment']] = 'CustomerInstallment'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.CustomerInstallmentActions[_PrismaModelT]':
        from .client import get_client

        return actions.CustomerInstallmentActions[_PrismaModelT](client or get_client(), cls)


class BaseCustomerComplaint(_PrismaModel):
    __prisma_model__: ClassVar[Literal['CustomerComplaint']] = 'CustomerComplaint'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.CustomerComplaintActions[_PrismaModelT]':
        from .client import get_client

        return actions.CustomerComplaintActions[_PrismaModelT](client or get_client(), cls)


class BaseCustomerTreatmentPlan(_PrismaModel):
    __prisma_model__: ClassVar[Literal['CustomerTreatmentPlan']] = 'CustomerTreatmentPlan'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.CustomerTreatmentPlanActions[_PrismaModelT]':
        from .client import get_client

        return actions.CustomerTreatmentPlanActions[_PrismaModelT](client or get_client(), cls)


class BaseCustomerServiceTab(_PrismaModel):
    __prisma_model__: ClassVar[Literal['CustomerServiceTab']] = 'CustomerServiceTab'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.CustomerServiceTabActions[_PrismaModelT]':
        from .client import get_client

        return actions.CustomerServiceTabActions[_PrismaModelT](client or get_client(), cls)


class BaseCustomerCareHistory(_PrismaModel):
    __prisma_model__: ClassVar[Literal['CustomerCareHistory']] = 'CustomerCareHistory'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.CustomerCareHistoryActions[_PrismaModelT]':
        from .client import get_client

        return actions.CustomerCareHistoryActions[_PrismaModelT](client or get_client(), cls)


class BaseMarketingTicketExtension(_PrismaModel):
    __prisma_model__: ClassVar[Literal['MarketingTicketExtension']] = 'MarketingTicketExtension'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.MarketingTicketExtensionActions[_PrismaModelT]':
        from .client import get_client

        return actions.MarketingTicketExtensionActions[_PrismaModelT](client or get_client(), cls)


class BaseMarketingTicketGroup(_PrismaModel):
    __prisma_model__: ClassVar[Literal['MarketingTicketGroup']] = 'MarketingTicketGroup'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.MarketingTicketGroupActions[_PrismaModelT]':
        from .client import get_client

        return actions.MarketingTicketGroupActions[_PrismaModelT](client or get_client(), cls)


