from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'Branch',
    'Service',
    'ServiceGroup',
    'ServiceType',
    'Employee',
    'EmployeeGroup',
    'User',
    'CustomerSource',
    'Membership',
    'City',
    'District',
    'Ward',
    'DailyRevenue',
    'Customer',
    'DailyCustomer',
    'Appointment',
    'Treatment',
    'CrawlLog',
    'CustomerPayment',
    'CustomerInstallment',
    'CustomerComplaint',
    'CustomerTreatmentPlan',
    'CustomerServiceTab',
    'CustomerCareHistory',
    'MarketingTicketExtension',
    'MarketingTicketGroup',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'Branch': {
        'employees': 'Employee',
        'users': 'User',
        'revenues': 'DailyRevenue',
        'daily_customers': 'DailyCustomer',
        'customers': 'Customer',
        'appointments': 'Appointment',
        'treatments': 'Treatment',
    },
    'Service': {
    },
    'ServiceGroup': {
    },
    'ServiceType': {
    },
    'Employee': {
        'branch': 'Branch',
    },
    'EmployeeGroup': {
    },
    'User': {
        'branch': 'Branch',
    },
    'CustomerSource': {
        'daily_customers': 'DailyCustomer',
        'customers': 'Customer',
    },
    'Membership': {
        'customers': 'Customer',
    },
    'City': {
        'districts': 'District',
    },
    'District': {
        'city': 'City',
        'wards': 'Ward',
    },
    'Ward': {
        'district': 'District',
    },
    'DailyRevenue': {
        'branch': 'Branch',
    },
    'Customer': {
        'branch': 'Branch',
        'source': 'CustomerSource',
        'membership': 'Membership',
        'appointments': 'Appointment',
        'treatments': 'Treatment',
        'payments': 'CustomerPayment',
        'installments': 'CustomerInstallment',
        'complaints': 'CustomerComplaint',
        'treatment_plans': 'CustomerTreatmentPlan',
        'service_tabs': 'CustomerServiceTab',
        'care_history': 'CustomerCareHistory',
    },
    'DailyCustomer': {
        'branch': 'Branch',
        'source': 'CustomerSource',
    },
    'Appointment': {
        'customer': 'Customer',
        'branch': 'Branch',
    },
    'Treatment': {
        'customer': 'Customer',
        'branch': 'Branch',
    },
    'CrawlLog': {
    },
    'CustomerPayment': {
        'customer': 'Customer',
    },
    'CustomerInstallment': {
        'customer': 'Customer',
    },
    'CustomerComplaint': {
        'customer': 'Customer',
    },
    'CustomerTreatmentPlan': {
        'customer': 'Customer',
    },
    'CustomerServiceTab': {
        'customer': 'Customer',
    },
    'CustomerCareHistory': {
        'customer': 'Customer',
    },
    'MarketingTicketExtension': {
    },
    'MarketingTicketGroup': {
    },
}

# fmt: on